model_list:
  - model_name: gpt-4o
    litellm_params:
      model: gpt-4o
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4o-mini
    litellm_params:
      model: gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY

general_settings:
  master_key: "sk-8VgdPnfbA_8V1fFxjyFPJhQr_km_XOYYcY2OORuq4KE"

environment_variables:
  OPENAI_API_KEY: "k3ESyXcfJWlOobuvL8MJWBIZRIXyeS4pNRL1fPtoxEZA8lW4x1u8zSXM85DvLhCh"
